name: Data Cleaner

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'trigger source'
        required: false
        default: 'cron-job.org'

jobs:
  tracker2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Sync profile
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          mkdir -p python

          # Hapus file lama jika ada
          if compgen -G "python/*.py" > /dev/null; then
            rm python/*.py
          fi

          # Acak dan rename aman terhadap spasi
          find backup/python -maxdepth 1 -type f -name "*.py" -print0 \
            | shuf -z \
            | awk -v RS='\0' '{print NR "|" $0}' \
            | while IFS="|" read -r num file; do
                cp "$file" "python/${num}.py"
              done

          git add python
          git commit -m "push code" || echo "No changes to commit"
          git push
